name: Create New Release
run-name: Create new release by @${{ github.actor }}

on:
  push:
    paths:
     - 'module.json'

jobs:
  buildRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JSON property extractor
        id: json_extracter
        uses: chrisfactory/GithubActions@1.0.0.4
        with:
          path: module.json
          properties: version

      # Substitute the Manifest and Download URLs in the module.json
      - name: Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: "module.json"
        env:
          url: https://github.com/${{ github.repository }}
          manifest: https://github.com/${{ github.repository }}/releases/latest/download/module.json
          download: https://github.com/${{ github.repository }}/releases/download/v${{ steps.json_extracter.outputs.version }}/jay-macros.zip
          changelog: https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md
          readme: https://github.com/${{ github.repository }}/blob/main/README.md

      # Create a zip file with all files required by the module to add to the release
      - run: zip -r ./jay-macros.zip module.json LICENSE lang/ scripts/ images/

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./module.json, ./jay-macros.zip"
          tag: "v${{ steps.json_extracter.outputs.version }}"
          commit: main
          body: "${{ github.event.head_commit.message }}"
